import 'dart:io';
import '../models/admin_upload.dart';
import '../models/song.dart';
import '../models/artist.dart';
import '../models/album.dart';
import 'supabase_service.dart';

/// Service to handle admin content moderation and artist uploads
class AdminService {
  static final AdminService _instance = AdminService._internal();
  factory AdminService() => _instance;
  AdminService._internal();

  final SupabaseService _supabaseService = SupabaseService();

  // ============================================
  // UPLOAD SUBMISSION (Artist/User)
  // ============================================

  /// Submit a new upload for admin review
  Future<AdminUpload?> submitUpload({
    required String uploaderId,
    required String artistName,
    required String songTitle,
    String? albumTitle,
    String? genre,
    String? language,
    required File audioFile,
    File? coverImage,
  }) async {
    try {
      // Generate unique paths for uploads
      final timestamp = DateTime.now().millisecondsSinceEpoch;
      final audioFileName = audioFile.path.split('/').last;
      final audioPath = 'uploads/$uploaderId/$timestamp-$audioFileName';

      // Upload audio file
      print('Uploading audio file...');
      await _supabaseService.uploadFile(audioFile, audioPath);

      // Upload cover image if provided
      String? coverPath;
      if (coverImage != null) {
        final coverFileName = coverImage.path.split('/').last;
        coverPath = 'uploads/$uploaderId/covers/$timestamp-$coverFileName';
        print('Uploading cover image...');
        await _supabaseService.uploadFile(coverImage, coverPath);
      }

      // Create upload record
      final upload = AdminUpload(
        id: '', // Will be generated by Supabase
        uploaderId: uploaderId,
        artistName: artistName,
        songTitle: songTitle,
        albumTitle: albumTitle,
        genre: genre,
        language: language ?? 'en',
        storagePath: audioPath,
        coverImage: coverPath,
        status: UploadStatus.pending,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final savedUpload = await _supabaseService.createUpload(upload);
      print('Upload submitted successfully!');
      return savedUpload;
    } catch (e) {
      print('Error submitting upload: $e');
      return null;
    }
  }

  /// Get user's upload history
  Future<List<AdminUpload>> getUserUploads(String userId) async {
    try {
      return await _supabaseService.getUserUploads(userId);
    } catch (e) {
      print('Error getting user uploads: $e');
      return [];
    }
  }

  // ============================================
  // ADMIN MODERATION
  // ============================================

  /// Get all pending uploads (admin only)
  Future<List<AdminUpload>> getPendingUploads() async {
    try {
      return await _supabaseService.getPendingUploads();
    } catch (e) {
      print('Error getting pending uploads: $e');
      return [];
    }
  }

  /// Approve an upload and move it to production
  Future<bool> approveUpload(String uploadId, String reviewerId) async {
    try {
      // Get upload details
      final uploads = await _supabaseService.getPendingUploads();
      final upload = uploads.firstWhere((u) => u.id == uploadId);

      // 1. Create or get artist
      final artist = await _getOrCreateArtist(
        upload.artistName,
        verified: true,
      );

      // 2. Create or get album (if provided)
      Album? album;
      if (upload.albumTitle != null && upload.albumTitle!.isNotEmpty) {
        album = await _getOrCreateAlbum(
          upload.albumTitle!,
          artist.id,
          upload.coverImage,
        );
      }

      // 3. Move audio file to production path
      final prodAudioPath = 'songs/${artist.id}/${upload.songTitle.replaceAll(' ', '-').toLowerCase()}.mp3';
      // TODO: Implement file move in Supabase Storage
      // For now, we'll use the upload path directly

      // 4. Move cover image to production path (if exists)
      String? prodCoverPath;
      if (upload.coverImage != null) {
        prodCoverPath = album != null
            ? 'albums/${album.id}/cover.jpg'
            : 'songs/${artist.id}/${upload.songTitle.replaceAll(' ', '-').toLowerCase()}-cover.jpg';
        // TODO: Implement file move
      }

      // 5. Create song record
      final song = Song(
        id: '', // Will be generated
        artistId: artist.id,
        albumId: album?.id,
        title: upload.songTitle,
        genre: upload.genre,
        language: upload.language,
        storagePath: upload.storagePath, // Using upload path for now
        isLocal: true,
        explicit: false,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // TODO: Create song in database
      // await _supabaseService.createSong(song);

      // 6. Update upload status
      await _supabaseService.updateUploadStatus(
        uploadId,
        UploadStatus.approved,
        reviewerId: reviewerId,
      );

      print('Upload approved successfully!');
      return true;
    } catch (e) {
      print('Error approving upload: $e');
      return false;
    }
  }

  /// Reject an upload
  Future<bool> rejectUpload(
    String uploadId,
    String reviewerId,
    String reason,
  ) async {
    try {
      await _supabaseService.updateUploadStatus(
        uploadId,
        UploadStatus.rejected,
        reviewerId: reviewerId,
        rejectionReason: reason,
      );

      print('Upload rejected');
      return true;
    } catch (e) {
      print('Error rejecting upload: $e');
      return false;
    }
  }

  /// Delete upload and associated files
  Future<bool> deleteUpload(String uploadId) async {
    try {
      // Get upload details
      final uploads = await _supabaseService.getPendingUploads();
      final upload = uploads.firstWhere((u) => u.id == uploadId);

      // Delete audio file
      await _supabaseService.deleteFile(upload.storagePath);

      // Delete cover image if exists
      if (upload.coverImage != null) {
        await _supabaseService.deleteFile(upload.coverImage!);
      }

      // TODO: Delete upload record from database
      // await _supabaseService.deleteUpload(uploadId);

      print('Upload deleted');
      return true;
    } catch (e) {
      print('Error deleting upload: $e');
      return false;
    }
  }

  // ============================================
  // HELPER METHODS
  // ============================================

  /// Get existing artist or create new one
  Future<Artist> _getOrCreateArtist(String artistName, {bool verified = true}) async {
    try {
      // TODO: Search for existing artist by name
      // For now, create new artist
      
      final artist = Artist(
        id: '', // Will be generated
        name: artistName,
        country: 'NG',
        verified: verified,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // TODO: Create artist in database
      // final savedArtist = await _supabaseService.createArtist(artist);
      // return savedArtist;

      return artist; // Placeholder
    } catch (e) {
      print('Error getting/creating artist: $e');
      rethrow;
    }
  }

  /// Get existing album or create new one
  Future<Album> _getOrCreateAlbum(
    String albumTitle,
    String artistId,
    String? coverImage,
  ) async {
    try {
      // TODO: Search for existing album by title and artist
      // For now, create new album

      final album = Album(
        id: '', // Will be generated
        artistId: artistId,
        title: albumTitle,
        coverImage: coverImage,
        releaseDate: DateTime.now(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // TODO: Create album in database
      // final savedAlbum = await _supabaseService.createAlbum(album);
      // return savedAlbum;

      return album; // Placeholder
    } catch (e) {
      print('Error getting/creating album: $e');
      rethrow;
    }
  }

  // ============================================
  // CONTENT VALIDATION
  // ============================================

  /// Validate audio file
  bool validateAudioFile(File file) {
    try {
      final fileName = file.path.split('/').last.toLowerCase();
      final extension = fileName.split('.').last;

      // Check extension
      if (!['mp3', 'wav', 'm4a'].contains(extension)) {
        return false;
      }

      // Check file size (max 50MB)
      final fileSizeInBytes = file.lengthSync();
      final fileSizeInMB = fileSizeInBytes / (1024 * 1024);
      if (fileSizeInMB > 50) {
        return false;
      }

      return true;
    } catch (e) {
      print('Error validating audio file: $e');
      return false;
    }
  }

  /// Validate image file
  bool validateImageFile(File file) {
    try {
      final fileName = file.path.split('/').last.toLowerCase();
      final extension = fileName.split('.').last;

      // Check extension
      if (!['jpg', 'jpeg', 'png'].contains(extension)) {
        return false;
      }

      // Check file size (max 5MB)
      final fileSizeInBytes = file.lengthSync();
      final fileSizeInMB = fileSizeInBytes / (1024 * 1024);
      if (fileSizeInMB > 5) {
        return false;
      }

      return true;
    } catch (e) {
      print('Error validating image file: $e');
      return false;
    }
  }
}
