import 'dart:math';
import '../models/song.dart';
import '../models/daily_feed.dart';
import '../models/user_profile.dart';
import 'supabase_service.dart';

/// Service to generate personalized music recommendations
class RecommendationService {
  static final RecommendationService _instance = RecommendationService._internal();
  factory RecommendationService() => _instance;
  RecommendationService._internal();

  final SupabaseService _supabaseService = SupabaseService();
  final Random _random = Random();

  // ============================================
  // DAILY FEED GENERATION
  // ============================================

  /// Generate a personalized daily worship feed for a user
  Future<DailyFeed?> generateDailyFeed(String userId) async {
    try {
      // Check if user already has a valid feed for today
      final existingFeed = await _supabaseService.getUserDailyFeed(userId);
      if (existingFeed != null && existingFeed.isValid) {
        return existingFeed;
      }

      // Get user profile for preferences
      final userProfile = await _supabaseService.getUserProfile(userId);
      final preferences = userProfile?.preferences ?? UserPreferences();

      // Get time of day
      final now = DateTime.now();
      final hour = now.hour;

      // Determine feed characteristics based on time of day
      String feedTitle;
      String feedDescription;
      List<String>? preferredGenres;

      if (hour >= 4 && hour < 12) {
        feedTitle = 'Your Morning Worship';
        feedDescription = 'Start your day with these uplifting songs';
        preferredGenres = ['Worship', 'Praise'];
      } else if (hour >= 12 && hour < 17) {
        feedTitle = 'Afternoon Inspiration';
        feedDescription = 'Keep your spirit high throughout the day';
        preferredGenres = ['Gospel', 'Contemporary Christian'];
      } else if (hour >= 17 && hour < 21) {
        feedTitle = 'Evening Reflection';
        feedDescription = 'Wind down with these peaceful melodies';
        preferredGenres = ['Worship', 'Afro-Gospel'];
      } else {
        feedTitle = 'Night Prayer & Worship';
        feedDescription = 'End your day in His presence';
        preferredGenres = ['Worship'];
      }

      // Generate song list (8-10 songs)
      final songs = await _generateRecommendedSongs(
        userId: userId,
        preferences: preferences,
        preferredGenres: preferredGenres,
        count: 8 + _random.nextInt(3), // 8-10 songs
      );

      if (songs.isEmpty) {
        print('No songs available for daily feed');
        return null;
      }

      // Create daily feed
      final feed = DailyFeed(
        id: '', // Will be generated by Supabase
        userId: userId,
        title: feedTitle,
        description: feedDescription,
        songIds: songs.map((s) => s.id).toList(),
        generatedAt: now,
        expiresAt: DateTime(now.year, now.month, now.day, 23, 59, 59),
        createdAt: now,
        songs: songs,
      );

      // Save to database
      final savedFeed = await _supabaseService.createDailyFeed(feed);
      return savedFeed;
    } catch (e) {
      print('Error generating daily feed: $e');
      return null;
    }
  }

  /// Generate recommended songs based on user preferences
  Future<List<Song>> _generateRecommendedSongs({
    required String userId,
    required UserPreferences preferences,
    List<String>? preferredGenres,
    int count = 10,
  }) async {
    try {
      final List<Song> recommendedSongs = [];

      // Get user's recently played songs to avoid repetition
      // TODO: Implement play history tracking
      // final recentlyPlayed = await _supabaseService.getRecentlyPlayed(userId);

      // Strategy 1: Get songs from preferred genres (40%)
      if (preferredGenres != null && preferredGenres.isNotEmpty) {
        final genreSongs = await _supabaseService.fetchSongs(
          genre: preferredGenres[_random.nextInt(preferredGenres.length)],
          limit: (count * 0.4).ceil(),
        );
        recommendedSongs.addAll(genreSongs.take((count * 0.4).ceil()));
      }

      // Strategy 2: Get trending songs (30%)
      final trendingSongs = await _supabaseService.getTrendingSongs(
        limit: (count * 0.3).ceil(),
      );
      recommendedSongs.addAll(trendingSongs.take((count * 0.3).ceil()));

      // Strategy 3: Get new releases (30%)
      final newReleases = await _supabaseService.getNewReleases(
        limit: (count * 0.3).ceil(),
      );
      recommendedSongs.addAll(newReleases.take((count * 0.3).ceil()));

      // Shuffle and limit to requested count
      recommendedSongs.shuffle(_random);
      return recommendedSongs.take(count).toList();
    } catch (e) {
      print('Error generating recommended songs: $e');
      return [];
    }
  }

  // ============================================
  // GENERAL RECOMMENDATIONS
  // ============================================

  /// Get personalized recommendations for a user
  Future<List<Song>> getRecommendations(
    String userId, {
    String? genre,
    int limit = 20,
  }) async {
    try {
      final userProfile = await _supabaseService.getUserProfile(userId);
      final preferences = userProfile?.preferences ?? UserPreferences();

      return await _generateRecommendedSongs(
        userId: userId,
        preferences: preferences,
        preferredGenres: genre != null ? [genre] : preferences.genres,
        count: limit,
      );
    } catch (e) {
      print('Error getting recommendations: $e');
      return [];
    }
  }

  /// Get trending songs
  Future<List<Song>> getTrendingSongs({String? genre, int limit = 20}) async {
    try {
      return await _supabaseService.getTrendingSongs(
        genre: genre,
        limit: limit,
      );
    } catch (e) {
      print('Error getting trending songs: $e');
      return [];
    }
  }

  /// Get new releases
  Future<List<Song>> getNewReleases({String? genre, int limit = 20}) async {
    try {
      return await _supabaseService.getNewReleases(
        genre: genre,
        limit: limit,
      );
    } catch (e) {
      print('Error getting new releases: $e');
      return [];
    }
  }

  /// Get songs by mood
  Future<List<Song>> getSongsByMood(String mood, {int limit = 20}) async {
    try {
      // Map moods to genres
      String? genre;
      switch (mood.toLowerCase()) {
        case 'worship':
          genre = 'Worship';
          break;
        case 'praise':
          genre = 'Praise';
          break;
        case 'reflection':
          genre = 'Gospel';
          break;
        case 'celebration':
          genre = 'Afro-Gospel';
          break;
        default:
          genre = null;
      }

      return await _supabaseService.fetchSongs(
        genre: genre,
        limit: limit,
      );
    } catch (e) {
      print('Error getting songs by mood: $e');
      return [];
    }
  }

  // ============================================
  // SEARCH & DISCOVERY
  // ============================================

  /// Search songs by query
  Future<List<Song>> searchSongs(String query, {int limit = 50}) async {
    try {
      return await _supabaseService.fetchSongs(
        searchQuery: query,
        limit: limit,
      );
    } catch (e) {
      print('Error searching songs: $e');
      return [];
    }
  }

  /// Get songs by artist
  Future<List<Song>> getSongsByArtist(String artistId, {int limit = 50}) async {
    try {
      return await _supabaseService.fetchSongs(
        artistId: artistId,
        limit: limit,
      );
    } catch (e) {
      print('Error getting songs by artist: $e');
      return [];
    }
  }

  /// Get songs by album
  Future<List<Song>> getSongsByAlbum(String albumId, {int limit = 50}) async {
    try {
      return await _supabaseService.fetchSongs(
        albumId: albumId,
        limit: limit,
      );
    } catch (e) {
      print('Error getting songs by album: $e');
      return [];
    }
  }

  // ============================================
  // FUTURE: AI-POWERED RECOMMENDATIONS
  // ============================================

  /// Generate AI-powered recommendations (placeholder for future implementation)
  /// This would call a serverless function that uses OpenAI/Gemini
  Future<List<Song>> getAIRecommendations(
    String userId, {
    String? mood,
    String? occasion,
    int limit = 10,
  }) async {
    // TODO: Implement AI recommendations
    // 1. Gather user context (listening history, preferences, time of day)
    // 2. Call serverless function with context
    // 3. Parse AI response and fetch songs
    // 4. Return personalized playlist
    
    print('AI recommendations not yet implemented. Using rule-based fallback.');
    return await getRecommendations(userId, limit: limit);
  }
}
